# Generated by Django 5.1.4 on 2025-01-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developerskills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Developer',
        ),
    ]
