# Generated by Django 5.1.4 on 2025-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developerskills', '0002_rename_teacher_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
